name: Test Conversion of All Guides
on:
  pull_request:
    types:
      - labeled

jobs:

  testingConversion:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        guides: ${{fromJson(needs.matrix.outputs.matrix)}}
    if: github.event.label.name == 'TestAll'

    steps:

      - uses: actions/checkout@master
        
      - name: Checkout Guide Converter repo
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/cloud-hosted-guide-converter
          path: GuideConverter

        
      - name: Checkout instructions
        uses: actions/checkout@v2
        with:
          repository: jakub-pomykala/cloud-hosted-guides
          path: GuideConverter/cloud-hosted-guides
          ref: ${{ github.event.pull_request.branch }}

      - uses: actions/setup-java@v1
        with:
          java-version: '15' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: Get Guide name
        run: |
          cd GuideConverter
          mvn -Dtest=TestConversion test -DguideName="cloud-hosted-guides/instructions/cloud-hosted-${{fromJson(needs.matrix.outputs.matrix)}}/instructions"